
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf  
      - ./db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql


  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db-data: